export type EmbeddedTask={id:string;title:string;goal:string;hint:string;starter:string;verify:(events:string[],input:{button:boolean;pot:number;command:string})=>boolean;project?:boolean};
const code=(body:string)=>`#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n${body.split('\n').map(line=>`    ${line}`).join('\n')}\n    return 0;\n}\n`;
export const embeddedTasks:EmbeddedTask[]=[
  {id:'blink-led',title:'Blink LED',goal:'Enciende LED 13, espera 500 ms y apágalo.',hint:'Usa gpio_write(13, 1), delay_ms(500) y gpio_write(13, 0).',starter:code('gpio_write(13, 1);\ndelay_ms(500);\ngpio_write(13, 0);'),verify:e=>e.includes('LED:13:1')&&e.includes('WAIT:500')&&e.includes('LED:13:0')},
  {id:'button-led',title:'Button controls LED',goal:'Haz que el botón controle LED 13.',hint:'button_read() devuelve 1 cuando el botón está pulsado.',starter:code('gpio_write(13, button_read() ? 1 : 0);'),verify:(e,i)=>e.includes(`LED:13:${i.button?1:0}`)},
  {id:'read-pot',title:'Read potentiometer',goal:'Lee el ADC y envía su valor al monitor.',hint:'adc_read(0) devuelve un valor entre 0 y 1023.',starter:code('int value = adc_read(0);\nprintf("ADC:%d\\n", value);'),verify:(e,i)=>e.includes(`ADC:${i.pot}`)},
  {id:'pot-brightness',title:'Pot controls brightness',goal:'Convierte ADC 0–1023 en PWM 0–100%.',hint:'Calcula adc_read(0) * 100 / 1023.',starter:code('int duty = adc_read(0) * 100 / 1023;\npwm_write(13, duty);'),verify:(e,i)=>e.includes(`PWM:13:${Math.floor(i.pot*100/1023)}`)},
  {id:'motor-pwm',title:'PWM motor speed',goal:'Controla el motor con PWM del potenciómetro.',hint:'Usa pwm_write(5, duty). El modelo muestra RPM = duty * 30.',starter:code('int duty = adc_read(0) * 100 / 1023;\npwm_write(5, duty);'),verify:e=>e.some(line=>line.startsWith('PWM:5:')),project:true},
  {id:'uart-echo',title:'UART echo',goal:'Responde con el mismo texto recibido.',hint:'uart_read() devuelve un const char*.',starter:code('uart_init(115200);\nuart_print(uart_read());'),verify:(e,i)=>e.includes(`UART:${i.command}`)},
  {id:'uart-parser',title:'UART command parser',goal:'Acepta LED ON, LED OFF y STATUS.',hint:'Compara strings con strcmp(input, "LED ON") == 0.',starter:code('const char *input = uart_read();\nif (strcmp(input, "LED ON") == 0) { gpio_write(13, 1); uart_print("LED enabled"); }\nelse if (strcmp(input, "LED OFF") == 0) { gpio_write(13, 0); uart_print("LED disabled"); }\nelse if (strcmp(input, "STATUS") == 0) uart_print(button_read() ? "LED: ON" : "LED: OFF");'),verify:(e,i)=>i.command==='LED ON'?e.includes('LED:13:1'):i.command==='LED OFF'?e.includes('LED:13:0'):i.command==='STATUS'?e.some(line=>line.startsWith('UART:LED:')):false,project:true},
  {id:'button-interrupt',title:'Button interrupt',goal:'Registra un evento de interrupción cuando se pulsa.',hint:'Llama interrupt_enable(1) y registra el evento del botón.',starter:code('interrupt_enable(1);\nif (button_read()) printf("IRQ:BUTTON\\n");'),verify:(e,i)=>e.includes('INTERRUPT:1')&&(!i.button||e.includes('IRQ:BUTTON'))},
  {id:'state-machine',title:'Simple state machine',goal:'Emite IDLE y luego ACTIVE al pulsar.',hint:'Representa los estados con un enum o constantes.',starter:code('printf("STATE:IDLE\\n");\nif (button_read()) printf("STATE:ACTIVE\\n");'),verify:(e,i)=>e.includes('STATE:IDLE')&&(!i.button||e.includes('STATE:ACTIVE'))},
  {id:'traffic-light',title:'Traffic light',goal:'Crea la secuencia RED 5 s → GREEN 5 s → YELLOW 2 s.',hint:'Usa traffic_set y delay_ms con 5000, 5000 y 2000.',starter:code('traffic_set("RED"); delay_ms(5000);\ntraffic_set("GREEN"); delay_ms(5000);\ntraffic_set("YELLOW"); delay_ms(2000);'),verify:e=>['TRAFFIC:RED','WAIT:5000','TRAFFIC:GREEN','WAIT:5000','TRAFFIC:YELLOW','WAIT:2000'].every((line,i)=>e[i]===line),project:true},
];
export const embeddedProjects=embeddedTasks.filter(item=>item.project);
export const embeddedPrelude=(input:{button:boolean;pot:number;command:string})=>`#include <stdio.h>\n#include <string.h>\n#define CB_BUTTON ${input.button?1:0}\n#define CB_POT ${Math.max(0,Math.min(1023,input.pot|0))}\nstatic const char *CB_COMMAND = ${JSON.stringify(input.command)};\nvoid gpio_write(int pin,int value){printf("LED:%d:%d\\n",pin,value?1:0);}\nint button_read(void){return CB_BUTTON;}\nint adc_read(int channel){(void)channel;return CB_POT;}\nvoid pwm_write(int pin,int duty){if(duty<0)duty=0;if(duty>100)duty=100;printf("PWM:%d:%d\\n",pin,duty);}\nvoid uart_init(int baud){printf("UART_BAUD:%d\\n",baud);}\nvoid uart_print(const char *text){printf("UART:%s\\n",text);}\nconst char *uart_read(void){return CB_COMMAND;}\nvoid delay_ms(int ms){printf("WAIT:%d\\n",ms);}\nvoid interrupt_enable(int enabled){printf("INTERRUPT:%d\\n",enabled?1:0);}\nvoid i2c_write(int address,int value){printf("I2C:%d:%d\\n",address,value);}\nvoid spi_write(int value){printf("SPI:%d\\n",value);}\nvoid traffic_set(const char *color){printf("TRAFFIC:%s\\n",color);}\n`;
