import type { Exercise, Language, LearningTrack, Lesson, LessonSection, TrackId } from '../types';

export const languages: { id: Language; name: string }[] = [{ id: 'python', name: 'Python' }, { id: 'c', name: 'C' }, { id: 'cpp', name: 'C++' }];

type Task = {
  id: string; title: string; prompt: string; pair?: boolean;
  py: string; c: string; cpp: string;
  cases: { nums: number[]; target?: number; expected: number }[];
  hint: string; why: string; time: string;
};
const task = (id: string, title: string, prompt: string, py: string, c: string, cpp: string, cases: Task['cases'], hint: string, why: string, time = 'O(n)', pair = false): Task => ({ id, title, prompt, py, c, cpp, cases, hint, why, time, pair });
const tasks: Task[] = [
  task('array-sum','Array Sum','Return the sum of every value.', 'return sum(nums)', 'int s=0; for(int i=0;i<n;i++) s+=a[i]; return s;', 'int s=0; for(int x:nums) s+=x; return s;', [{nums:[2,3,5],expected:10},{nums:[],expected:0},{nums:[-5,2,1],expected:-2}], 'Keep a running total.', 'A single pass adds each element once.'),
  task('maximum-value','Maximum Value','Return the largest value; return 0 for an empty list.', 'return max(nums, default=0)', 'if(!n)return 0; int m=a[0]; for(int i=1;i<n;i++) if(a[i]>m)m=a[i]; return m;', 'if(nums.empty())return 0; int m=nums[0]; for(int x:nums) if(x>m)m=x; return m;', [{nums:[3,9,2],expected:9},{nums:[],expected:0},{nums:[-4,-2],expected:-2}], 'Initialize from the first element, not zero.', 'Using zero as the initial maximum breaks all-negative inputs.'),
  task('count-even','Count Even','Count values divisible by two.', 'return sum(x % 2 == 0 for x in nums)', 'int count=0; for(int i=0;i<n;i++) if(a[i]%2==0)count++; return count;', 'int count=0; for(int x:nums) if(x%2==0)count++; return count;', [{nums:[1,2,4,7],expected:2},{nums:[],expected:0},{nums:[-2,0,3],expected:2}], 'The remainder of an even integer is zero.', 'A predicate can be counted with one pass.'),
  task('minimum-value','Minimum Value','Return the smallest value; return 0 for an empty list.', 'return min(nums, default=0)', 'if(!n)return 0; int m=a[0]; for(int i=1;i<n;i++) if(a[i]<m)m=a[i]; return m;', 'if(nums.empty())return 0; int m=nums[0]; for(int x:nums) if(x<m)m=x; return m;', [{nums:[3,9,2],expected:2},{nums:[],expected:0},{nums:[-4,-2],expected:-4}], 'Begin at the first value.', 'The minimum is updated only when a smaller value appears.'),
  task('first-index','First Index','Return the first index of target, or -1.', 'for i, value in enumerate(nums):\n        if value == target: return i\n    return -1', 'for(int i=0;i<n;i++) if(a[i]==target)return i; return -1;', 'for(int i=0;i<(int)nums.size();i++) if(nums[i]==target)return i; return -1;', [{nums:[4,8,8,2],target:8,expected:1},{nums:[],target:1,expected:-1},{nums:[1,2],target:3,expected:-1}], 'Stop at the first match.', 'Linear search works on unsorted data.', 'O(n)', true),
  task('last-index','Last Index','Return the last index of target, or -1.', 'answer = -1\n    for i, value in enumerate(nums):\n        if value == target: answer = i\n    return answer', 'int answer=-1; for(int i=0;i<n;i++) if(a[i]==target)answer=i; return answer;', 'int answer=-1; for(int i=0;i<(int)nums.size();i++) if(nums[i]==target)answer=i; return answer;', [{nums:[4,8,8,2],target:8,expected:2},{nums:[],target:1,expected:-1},{nums:[1,2],target:3,expected:-1}], 'Keep updating the answer when a match appears.', 'The final recorded index is the last match.', 'O(n)', true),
  task('count-target','Count Target','Count how often target appears.', 'return nums.count(target)', 'int count=0; for(int i=0;i<n;i++) if(a[i]==target)count++; return count;', 'int count=0; for(int x:nums) if(x==target)count++; return count;', [{nums:[2,1,2,2],target:2,expected:3},{nums:[],target:1,expected:0},{nums:[1,2],target:3,expected:0}], 'Compare every element with target.', 'Counting requires visiting all values.', 'O(n)', true),
  task('positive-count','Positive Count','Count strictly positive values.', 'return sum(x > 0 for x in nums)', 'int count=0; for(int i=0;i<n;i++) if(a[i]>0)count++; return count;', 'int count=0; for(int x:nums) if(x>0)count++; return count;', [{nums:[-1,0,5,8],expected:2},{nums:[],expected:0},{nums:[0,-3],expected:0}], 'Zero is not positive.', 'A comparison and counter are enough.'),
  task('unique-count','Unique Count','Return the number of distinct values.', 'return len(set(nums))', 'int count=0; for(int i=0;i<n;i++){int seen=0;for(int j=0;j<i;j++)if(a[j]==a[i])seen=1;if(!seen)count++;}return count;', 'return (int)unordered_set<int>(nums.begin(),nums.end()).size();', [{nums:[4,4,2,1,2],expected:3},{nums:[],expected:0},{nums:[7,7,7],expected:1}], 'A set stores one copy of each value.', 'The C version compares against earlier elements; a hash set reduces average time.', 'O(n) average with a set'),
  task('is-sorted','Is Sorted','Return 1 if values are nondecreasing, else 0.', 'return int(all(nums[i-1] <= nums[i] for i in range(1, len(nums))))', 'for(int i=1;i<n;i++) if(a[i-1]>a[i])return 0; return 1;', 'for(int i=1;i<(int)nums.size();i++) if(nums[i-1]>nums[i])return 0; return 1;', [{nums:[1,2,2,5],expected:1},{nums:[],expected:1},{nums:[2,1],expected:0}], 'Compare adjacent pairs.', 'One inversion proves the sequence is not sorted.'),
  task('binary-find','Binary Find','Return the index of target in a sorted array, or -1.', 'left, right = 0, len(nums)-1\n    while left <= right:\n        mid = (left+right)//2\n        if nums[mid] == target: return mid\n        if nums[mid] < target: left = mid+1\n        else: right = mid-1\n    return -1', 'int l=0,r=n-1;while(l<=r){int m=l+(r-l)/2;if(a[m]==target)return m;if(a[m]<target)l=m+1;else r=m-1;}return -1;', 'int l=0,r=(int)nums.size()-1;while(l<=r){int m=l+(r-l)/2;if(nums[m]==target)return m;if(nums[m]<target)l=m+1;else r=m-1;}return -1;', [{nums:[1,3,5,7],target:5,expected:2},{nums:[],target:1,expected:-1},{nums:[1,3,5],target:2,expected:-1}], 'Discard half of the remaining sorted range.', 'The invariant is that any possible answer remains between left and right.', 'O(log n)', true),
  task('lower-bound','Lower Bound','Return the first index whose value is at least target in a sorted array.', 'left, right = 0, len(nums)\n    while left < right:\n        mid = (left+right)//2\n        if nums[mid] < target: left = mid+1\n        else: right = mid\n    return left', 'int l=0,r=n;while(l<r){int m=l+(r-l)/2;if(a[m]<target)l=m+1;else r=m;}return l;', 'int l=0,r=(int)nums.size();while(l<r){int m=l+(r-l)/2;if(nums[m]<target)l=m+1;else r=m;}return l;', [{nums:[1,3,3,7],target:3,expected:1},{nums:[],target:1,expected:0},{nums:[1,3],target:9,expected:2}], 'Use a half-open interval [left, right).', 'The answer may equal the array length.', 'O(log n)', true),
  task('prefix-positive','Positive Prefix','Return the length of the longest initial run of positive values.', 'count = 0\n    for x in nums:\n        if x <= 0: break\n        count += 1\n    return count', 'int i=0;while(i<n&&a[i]>0)i++;return i;', 'int i=0;while(i<(int)nums.size()&&nums[i]>0)i++;return i;', [{nums:[1,2,-1,4],expected:2},{nums:[],expected:0},{nums:[2,3],expected:2}], 'Stop as soon as the condition fails.', 'A prefix ends at the first nonpositive value.'),
  task('adjacent-diff','Largest Adjacent Gap','Return the largest absolute difference between neighbors; 0 if fewer than two values.', 'return max((abs(nums[i]-nums[i-1]) for i in range(1,len(nums))), default=0)', 'int m=0;for(int i=1;i<n;i++){int d=a[i]-a[i-1];if(d<0)d=-d;if(d>m)m=d;}return m;', 'int m=0;for(int i=1;i<(int)nums.size();i++)m=max(m,abs(nums[i]-nums[i-1]));return m;', [{nums:[1,8,5],expected:7},{nums:[4],expected:0},{nums:[],expected:0}], 'Start at index one.', 'Each adjacent pair is examined exactly once.'),
  task('longest-run','Longest Increasing Run','Return the length of the longest contiguous strictly increasing run.', 'best = current = 0\n    for i, x in enumerate(nums):\n        current = current + 1 if i and nums[i-1] < x else 1\n        best = max(best, current)\n    return best', 'int best=0,cur=0;for(int i=0;i<n;i++){cur=i&&a[i-1]<a[i]?cur+1:1;if(cur>best)best=cur;}return best;', 'int best=0,cur=0;for(int i=0;i<(int)nums.size();i++){cur=i&&nums[i-1]<nums[i]?cur+1:1;best=max(best,cur);}return best;', [{nums:[1,2,3,1,2],expected:3},{nums:[],expected:0},{nums:[3,2],expected:1}], 'Reset the current run when the order breaks.', 'Track current and best lengths in one pass.'),
  task('pair-count','Pairs Equal Target','Count unordered pairs of distinct indices whose values sum to target.', 'count = 0\n    for i in range(len(nums)):\n        for j in range(i+1,len(nums)):\n            if nums[i]+nums[j] == target: count += 1\n    return count', 'int count=0;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)if(a[i]+a[j]==target)count++;return count;', 'int count=0;for(int i=0;i<(int)nums.size();i++)for(int j=i+1;j<(int)nums.size();j++)if(nums[i]+nums[j]==target)count++;return count;', [{nums:[1,2,3,2],target:4,expected:2},{nums:[],target:0,expected:0},{nums:[2,2,2],target:4,expected:3}], 'Use i < j to count each pair once.', 'The nested loop is clear and correct; a frequency map can improve average time.', 'O(n²)', true),
  task('max-window','Best Two-Value Window','Return the largest sum of two adjacent values; 0 if fewer than two.', 'return max((nums[i-1]+nums[i] for i in range(1,len(nums))), default=0)', 'if(n<2)return 0;int best=a[0]+a[1];for(int i=2;i<n;i++)if(a[i-1]+a[i]>best)best=a[i-1]+a[i];return best;', 'if(nums.size()<2)return 0;int best=nums[0]+nums[1];for(int i=2;i<(int)nums.size();i++)best=max(best,nums[i-1]+nums[i]);return best;', [{nums:[1,5,2],expected:7},{nums:[],expected:0},{nums:[-5,-2,-3],expected:-5}], 'Reuse the two-value window as you move right.', 'Initialize from a real window so negative inputs work.'),
  task('zero-count','Zero Count','Count zero-valued elements.', 'return nums.count(0)', 'int count=0;for(int i=0;i<n;i++)if(a[i]==0)count++;return count;', 'return (int)count(nums.begin(),nums.end(),0);', [{nums:[0,1,0,-1],expected:2},{nums:[],expected:0},{nums:[1,2],expected:0}], 'A zero is a value, not an absent element.', 'The predicate checks equality with zero.'),
];
const taskById = Object.fromEntries(tasks.map(item => [item.id, item])) as Record<string, Task>;

function makeExercise(spec: Task, track: TrackId): Exercise {
  const params = spec.pair ? 'nums, target' : 'nums';
  const cparams = `int a[], int n${spec.pair ? ', int target' : ''}`;
  const cppparams = `vector<int> nums${spec.pair ? ', int target' : ''}`;
  const starter = { python: `def solve(${params}):\n    # Your code here\n    pass\n`, c: `int solve(${cparams}) {\n    // Your code here\n    return 0;\n}\n`, cpp: `#include <vector>\n#include <algorithm>\n#include <unordered_set>\n#include <cstdlib>\nusing namespace std;\nint solve(${cppparams}) {\n    // Your code here\n    return 0;\n}\n` };
  const solutions = { python: `def solve(${params}):\n    ${spec.py}\n`, c: `int solve(${cparams}) { ${spec.c} }`, cpp: `#include <vector>\n#include <algorithm>\n#include <unordered_set>\n#include <cstdlib>\nusing namespace std;\nint solve(${cppparams}) { ${spec.cpp} }` };
  return { id: `${track}-${spec.id}`, title: spec.title, difficulty: spec.time.includes('log') || spec.time.includes('²') ? 'Medium' : 'Easy', description: spec.prompt, examples: [`${JSON.stringify(spec.cases[0].nums)}${spec.pair ? `, ${spec.cases[0].target}` : ''} → ${spec.cases[0].expected}`], constraints: ['0 ≤ n ≤ 1000', 'Values fit in signed 32-bit integers'], starter, solutions, tests: spec.cases.map((item, index) => ({ input: JSON.stringify(spec.pair ? [item.nums, item.target] : item.nums), expected: String(item.expected), hidden: index === spec.cases.length - 1, timeout: 5000 })), hints: [spec.hint], explanation: spec.why, complexity: { time: spec.time, space: 'O(1) extra for the shown loop unless a set is used' }, signature: spec.pair ? 'array-target' : 'array' };
}

type Seed = { module: string; title: string; summary: string; learn: string; example: string; question: string; answers: [string,string,string]; correct: number; takeaway: string; exerciseIds: string[]; visual?: 'binary-search' | 'stack' | 'queue' | 'linked-list' | 'tree' | 'memory' | 'binary-hex' | 'register'; keywords?: string[] };
const seed = (module: string, title: string, summary: string, learn: string, example: string, question: string, answers: [string,string,string], correct: number, takeaway: string, exerciseIds: string[], visual?: Seed['visual'], keywords?: string[]): Seed => ({module,title,summary,learn,example,question,answers,correct,takeaway,exerciseIds,visual,keywords});

const algorithms: Seed[] = [
  seed('Foundations','Big O','Estimate how work grows as input grows.','O(n) means one pass for n elements. O(log n) repeatedly halves the search space. Ignore constant factors when comparing growth, but measure real performance when it matters.','A loop over 1,000 values performs about 1,000 checks; binary search needs about 10.', 'Which grows more slowly?', ['O(n²)','O(log n)','O(n)'],1,'State time and extra space separately.',['array-sum','count-even']),
  seed('Foundations','Arrays','Use indexed, contiguous sequences.','An index starts at zero. Reading an element by index is O(1); scanning all elements is O(n). Inserting near the front can shift many values.','[4, 8, 2] has 8 at index 1.','What is the final valid index of an array of length 4?',['4','3','0'],1,'Check empty input before reading index zero.',['maximum-value','minimum-value']),
  seed('Foundations','Hash Maps and Sets','Use keys for fast average lookup.','A set stores distinct keys. A map associates a key with a value such as a count. Hash operations are O(1) on average, with collision and memory costs.','Counting 2 in [2, 1, 2] gives {2: 2, 1: 1}.','Which stores unique keys without values?',['set','queue','stack'],0,'Use a map for counts and a set for membership.',['unique-count','count-target']),
  seed('Foundations','Stack and Queue','Choose LIFO or FIFO deliberately.','A stack removes the most recently pushed item. A queue removes the earliest enqueued item. Both support O(1) operations at their active ends.','Undo is stack shaped; a print job line is queue shaped.','Which item leaves a stack first after pushing 2, then 5?',['2','5','Neither'],1,'Name the end where items enter and leave.',['positive-count'], 'stack'),
  seed('Searching','Linear Search','Scan unsorted data safely.','Visit elements from left to right until a match is found. Return -1 when absent. A repeated value can have a first and a last position.','Searching 8 in [4, 8, 8] first finds index 1.','Does linear search require sorting?',['Yes','No','Only for duplicates'],1,'Linear search works even when the input is unsorted.',['first-index','last-index']),
  seed('Searching','Binary Search','Halve a sorted range at each step.','Keep left and right bounds around every possible answer. Inspect mid, then discard the half that cannot contain the target. An unsorted input breaks the argument.','In [1,3,5,7,9], searching 7 checks 5 then 7.','What must be true before ordinary binary search?',['Values are sorted','Values are unique','Length is even'],0,'Preserve a clear bound invariant.',['binary-find','lower-bound'],'binary-search'),
  seed('Linked Structures','Linked Lists','Follow references between nodes.','A node holds a value and a link to the next node. A known node can be inserted after in O(1), while finding an index takes O(n). A fast and slow pointer pair can detect cycles.','5 → 8 → 12 → null','Can a singly linked list jump to index 20 in O(1)?',['Yes','No','Only when sorted'],1,'Draw the links before changing pointers.',['prefix-positive'],'linked-list'),
  seed('Trees and Graphs','Tree Traversal','Visit nodes in a chosen order.','DFS explores a branch before another branch; BFS explores one level at a time. Preorder visits root first, inorder visits it between children, and postorder visits it last.','Tree 4 with children 2 and 6: inorder is 2,4,6.','Which traversal uses a queue?',['BFS','Recursive DFS','Inorder only'],0,'Record visited nodes in graphs to avoid cycles.',['longest-run'],'tree'),
  seed('Patterns','Two Pointers and Sliding Window','Track a moving range with small state.','Two pointers can scan from both ends of a sorted array. A sliding window updates an aggregate as its boundaries move. Prefix sums answer many fixed range sums after preprocessing.','For [1,5,2], the best adjacent two-value window sums to 7.','When moving a sum window, what leaves the sum?',['The outgoing left value','Every prior value','The new right value'],0,'Write down what enters and leaves the window.',['max-window','pair-count']),
  seed('Advanced','Recursion and Dynamic Programming','Break problems into smaller states.','Recursion requires a base case. Dynamic programming stores answers to repeated subproblems; greedy choices need a proof that a local decision stays optimal. A heap retrieves an extreme item efficiently.','Fibonacci memoization computes each n once instead of repeating branches.','What prevents infinite recursion?',['A base case','A heap','A hash collision'],0,'Define the state and transition before coding.',['is-sorted','adjacent-diff']),
];

const python: Seed[] = [
  seed('Basics','Variables and Types','Bind names to values and inspect their types.','Python variables refer to objects. Integers have arbitrary precision, booleans are a distinct type, and None represents no value. Choose names that explain the role of a value.','total = 0; total += 5','What does len([2,4]) return?',['1','2','4'],1,'Use type(value) while learning, then rely on clear contracts.',['array-sum','positive-count']),
  seed('Basics','Strings and Lists','Index, slice and iterate sequences.','Strings cannot be changed in place. Lists can. A slice creates a new sequence; negative indices count backward. Always handle the empty sequence.','items[-1] reads the last element when items is nonempty.','Which is mutable?',['str','list','tuple'],1,'Use enumerate when the index and value are both needed.',['maximum-value','minimum-value']),
  seed('Basics','Tuples, Dictionaries and Sets','Pick the collection that fits access.','Tuples group fixed values. Dictionaries map keys to values. Sets remove duplicates and offer average constant-time membership. A dictionary key must be hashable.','counts[x] = counts.get(x, 0) + 1','Which collection removes duplicates?',['list','set','tuple'],1,'Prefer dict.get for a default count.',['unique-count','count-target']),
  seed('Control Flow','Conditions and Loops','Make branches and loop bounds explicit.','if selects a branch. for iterates an iterable; while repeats while a condition holds. break exits a loop and continue moves to the next iteration.','for i, value in enumerate(nums): ...','What does break do?',['Exits the nearest loop','Skips only one statement','Restarts the function'],0,'Consider zero iterations and negative values.',['count-even','first-index']),
  seed('Functions','Parameters and Return','Give each function a clear contract.','Parameters provide inputs and return sends a value back. Scope keeps local names inside the function. A lambda is useful for a small expression, not complex control flow.','def double(x): return 2 * x','What does a function return without a return statement?',['0','None','False'],1,'Keep side effects separate from computed results.',['last-index']),
  seed('Intermediate','Comprehensions and Exceptions','Build collections clearly and handle failures.','A comprehension expresses a simple transformation or filter. Catch only expected exceptions; do not swallow errors silently. Use finally for cleanup when needed.','[x*x for x in nums if x > 0]','Which clause filters values in a comprehension?',['if','except','return'],0,'A normal loop is clearer for multi-step logic.',['zero-count']),
  seed('Intermediate','Classes and Modules','Group state and reuse code.','A class combines data with methods; self refers to the instance. Modules organize names. Import local modules explicitly so dependencies stay visible.','class Counter:\n    def __init__(self): self.value = 0','Where does instance state usually live?',['self','global','import'],0,'Use a class when state and behavior belong together.',['is-sorted']),
  seed('Intermediate','Files and Virtual Paths','Read and write within a virtual filesystem.','Pyodide supplies an in-memory filesystem inside the worker. File operations in lessons use that virtual environment; they do not read arbitrary files from the device. Close files with a with block.','with open("notes.txt", "w") as file: file.write("hello")','Where is a lesson file created?',['In the worker virtual filesystem','In device Documents','On a server'],0,'Treat file paths as data and handle missing files.',['prefix-positive']),
];

const c: Seed[] = [
  seed('Fundamentals','Variables and Types','Choose a type and understand its range.','C values have fixed representations. int is signed, char is byte-sized, and a conversion can lose information. Initialize variables before reading them.','int count = 0;','What must happen before reading a local variable?',['Initialize it','Free it','Cast it'],0,'Compile warnings are part of the feedback.',['array-sum','count-even']),
  seed('Fundamentals','Conditions and Loops','Control flow with explicit bounds.','if tests a condition. for and while repeat work. An array of length n has valid indices 0 through n-1; an off-by-one bug can access invalid memory.','for (int i=0; i<n; i++) { /* use a[i] */ }','Is a[n] valid for an array of length n?',['Yes','No','Only if n is even'],1,'Prefer i < n for a forward scan.',['maximum-value','positive-count']),
  seed('Fundamentals','Functions and Scope','Pass data through clear interfaces.','A C array parameter decays to a pointer, so pass its length separately. Local variables have automatic storage duration. Return a value of the declared type.','int sum(const int *a, int n);','Why pass n with an array parameter?',['The pointer does not carry length','To allocate the stack','To sort it'],0,'Document ownership when passing pointers.',['minimum-value']),
  seed('Memory','Addresses and Pointers','Distinguish an address from its value.','&x obtains an address; *p reads or writes the object it points to. Dereference only a valid pointer. Pointer arithmetic advances by element size.','int x=8; int *p=&x; *p=9;','What does *p mean when p is int*?',['The pointed-to int','The address value','A new allocation'],0,'Draw addresses and values separately.',['first-index'],'memory'),
  seed('Arrays','Arrays and C Strings','Keep bounds and terminators in mind.','C arrays have fixed storage. A C string is a char array ending in a zero byte. Copying without enough space causes undefined behavior.','char word[] = "hi"; // three bytes including \\0','How many bytes does "hi" need?',['2','3','4'],1,'Allocate space for the zero terminator.',['last-index','count-target']),
  seed('Structures','struct, enum and typedef','Group related fields and name states.','struct groups fields; enum names integral states. typedef creates an alias, not a new runtime object. Access a field through a pointer with ->.','struct Point { int x; int y; };','Which operator accesses a struct field through a pointer?',['.','->','&'],1,'Use an enum for a finite state machine.',['is-sorted']),
  seed('Memory','Stack and Heap','Understand object lifetime.','Automatic local objects usually live until the block ends. malloc and calloc allocate until free; realloc may move the block. Check allocation results and free each owned allocation once.','int *a = malloc(n * sizeof *a); if (a) free(a);','What must eventually follow successful malloc for owned memory?',['free','return 0','typedef'],0,'Never use a pointer after free.',['unique-count'],'memory'),
  seed('Memory','Pointer Arithmetic','Move within a known array.','Adding one to an int pointer advances by sizeof(int), not one byte. Pointer subtraction is defined within the same array. One-past-end can be compared but not dereferenced.','int *end = a + n;','Can you dereference a+n?',['Yes','No','Only for n=0'],1,'Keep every dereference within valid elements.',['adjacent-diff'],'memory'),
];

const cpp: Seed[] = [
  seed('Fundamentals','Variables, References and const','Make ownership and mutation clear.','A reference aliases an existing object. const prevents mutation through that name. Prefer const references for large read-only inputs.','int x=4; const int& view=x;','Does a reference normally refer to another object later?',['Yes','No','Only inside a vector'],1,'Use values for small types and references when aliasing is intended.',['array-sum','positive-count']),
  seed('Fundamentals','Functions and Overloads','Give functions precise signatures.','An overload differs by parameter types, not return type alone. Default arguments belong at the end. Keep interfaces small and document assumptions.','int twice(int x) { return 2*x; }','Can return type alone distinguish two overloads?',['Yes','No','Only with templates'],1,'Prefer one clear contract over ambiguous overloads.',['maximum-value']),
  seed('STL','vector, array and string','Choose dynamic or fixed storage.','vector grows dynamically and offers contiguous indexed access. array has a compile-time size. string manages character storage and length. Iterators can be invalidated by vector growth.','vector<int> values{2,4}; values.push_back(8);','Which container grows with push_back?',['array','vector','int'],1,'Check size before accessing front or back.',['minimum-value','count-even']),
  seed('STL','unordered_map, map and set','Match lookup, ordering and uniqueness.','unordered_map offers average O(1) lookup without sorted order. map maintains sorted keys in O(log n). set stores unique sorted keys. Choose the guarantee you need.','unordered_map<int,int> count; count[2]++;','Which stores sorted unique keys?',['set','vector','unordered_map'],0,'Do not rely on unordered_map iteration order.',['unique-count','count-target']),
  seed('STL','stack, queue and priority_queue','Use adapters for access patterns.','stack is LIFO, queue is FIFO, and priority_queue exposes the highest-priority element. Adapters do not support arbitrary indexed access.','priority_queue<int> q; q.push(3); q.push(8); // top is 8','Which adapter exposes the largest int by default?',['queue','stack','priority_queue'],2,'Choose based on removal order.',['prefix-positive'],'stack'),
  seed('OOP','Classes, Constructors and Objects','Keep invariants inside objects.','A constructor initializes an object. Private fields protect invariants and public methods express allowed operations. A destructor releases owned resources when needed.','class Counter { int value=0; public: void add(){++value;} };','When does a constructor run?',['At object creation','Only at program exit','After each method'],0,'Prefer standard containers over manual resource ownership.',['is-sorted']),
  seed('OOP','Inheritance and Polymorphism','Use virtual behavior when a shared interface fits.','A virtual function dispatches through a base reference or pointer. A polymorphic base generally needs a virtual destructor. Composition is often simpler than inheritance.','struct Device { virtual void run()=0; virtual ~Device()=default; };','Why virtual destructor in a polymorphic base?',['Safe deletion through base pointer','Faster sorting','Larger stack'],0,'Use inheritance for a true is-a relationship.',['zero-count']),
  seed('Algorithms','sort and find','Use standard algorithms with iterators.','sort rearranges a random-access range in O(n log n). find scans a range in O(n). Both use half-open [first,last) iterator ranges.','sort(v.begin(), v.end());','Does find require sorted input?',['Yes','No','Only for strings'],1,'Pass begin and end, not a last-element iterator.',['first-index','last-index']),
  seed('Algorithms','lower_bound and binary_search','Search sorted ranges.','lower_bound returns the first position not less than the target. binary_search reports whether a target exists. Both need a sorted range and run in O(log n) comparisons.','auto it = lower_bound(v.begin(), v.end(), x);','May lower_bound return end()?',['Yes','No','Only on empty vectors'],0,'Check end() before dereferencing the iterator.',['binary-find','lower-bound'],'binary-search'),
  seed('Algorithms','Complexity and Containers','Choose a structure from the needed operation.','For frequent membership use a hash set or map; for ordered traversal use map or set; for indexed scans use vector. A heap is useful when repeatedly extracting an extreme.','Need fast average lookup? unordered_map. Need sorted keys? map.','Which is best for indexed contiguous traversal?',['vector','map','priority_queue'],0,'State the dominant operation before choosing a container.',['max-window']),
];

const embedded: Seed[] = [
  seed('Foundations','Microcontrollers','Understand firmware and peripherals.','A microcontroller combines a CPU, memory and peripherals on one chip. Firmware configures those peripherals and responds to external events. Forge Virtual MCU is an educational model.','A GPIO pin can drive an LED or read a button.','What does GPIO describe?',['General-purpose digital pins','A file format','A processor instruction'],0,'Treat the board as an abstraction, not a specific device.',[]),
  seed('Foundations','Binary and Hex','Convert numbers and inspect bits.','Binary shows individual bits; hexadecimal groups them four at a time. 13 decimal is 00001101 binary and 0x0D hexadecimal.','0xA = 1010₂ = 10₁₀','How many bits does one hex digit represent?',['2','4','8'],1,'Group binary digits into nibbles from the right.',[],'binary-hex'),
  seed('Foundations','Bits and Registers','Set, clear and test register bits.','A register is a fixed-width value whose bits control hardware. OR sets a bit, AND with a complement clears it, and AND tests it. Never change reserved bits without a specification.','GPIO_CTRL |= (1u << 3);','Which operation sets bit 3 without clearing others?',['OR with 1<<3','AND with 1<<3','XOR with zero'],0,'Write the mask in binary before changing a register.',[],'register'),
  seed('Peripherals','GPIO and ADC','Read digital and analog inputs.','GPIO reads a digital low/high level. ADC samples an analog voltage into a number; resolution and reference voltage determine conversion. Debounce mechanical buttons.','A 10-bit ADC produces integer codes from 0 through 1023.','What does an ADC convert?',['Voltage to a digital code','PWM to UART','A byte to a pointer'],0,'Keep sampling assumptions visible.',[]),
  seed('Peripherals','PWM and Timers','Control duty cycle and periodic events.','PWM repeats a high/low signal; duty cycle is the high fraction. A timer can trigger periodic work. A simple educational motor model maps 100% duty to 3000 RPM.','70% duty → about 2100 RPM in this model.','Does 70% duty mean a constant 70% voltage?',['Yes','No, it is a high/low waveform','Only on UART'],1,'The model is illustrative, not a physical motor simulation.',[]),
  seed('Peripherals','Interrupts and UART','React to events and exchange serial bytes.','An interrupt requests attention from firmware; an ISR should do short work and defer heavy processing. UART sends asynchronous serial bytes at an agreed baud rate.','UART at 115200 baud can carry textual commands.','Where should lengthy parsing normally happen?',['Inside a long ISR','In the main loop or task','Inside a pin'],1,'Keep interrupt handlers short and predictable.',[]),
  seed('Buses','I2C and SPI','Connect external devices.','I2C uses shared data and clock lines with addressed devices. SPI uses clock and separate data directions plus chip select. Match voltage levels and timing requirements.','An I2C sensor has an address; an SPI sensor uses chip select.','Which bus normally has addressed devices on two shared wires?',['I2C','SPI','PWM'],0,'Read the device data sheet before choosing bus settings.',[]),
  seed('Control','State Machines','Make legal transitions explicit.','A finite state machine names states and events. A traffic light cycles through red, green and yellow with specified durations. Keep output behavior tied to state.','RED 5 s → GREEN 5 s → YELLOW 2 s → RED','What determines the next state?',['Current state and event/time','Only the color of a variable','A random pointer'],0,'List every transition before writing code.',[]),
  seed('Projects','Sensors and Motors','Turn input into bounded output.','Sample a potentiometer with ADC, clamp values, and map a duty cycle to a motor speed estimate. Feedback control needs additional modeling beyond this learning board.','ADC 512 of 1023 maps to roughly 50% duty.','Why clamp duty cycle?',['To keep it in 0–100%','To speed the CPU','To store a pointer'],0,'Document the mapping and units.',[]),
  seed('RTOS','RTOS and FreeRTOS','Coordinate tasks and shared state.','An RTOS schedules tasks; a queue passes messages, and a mutex protects shared state. Interrupt handlers use appropriate APIs. Timing guarantees depend on hardware and configuration.','A sensor task sends readings through a queue to a display task.','What protects one shared resource from simultaneous task access?',['Mutex','ADC','GPIO'],0,'Start with one task before adding concurrency.',[]),
];

function slug(text: string) { return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); }
function toLesson(item: Seed, track: TrackId): Lesson {
  const id = track === 'algorithms' && item.title === 'Arrays' ? 'arrays' : `${track}-${slug(item.title)}`;
  const sections: LessonSection[] = [
    {type:'text',title:'Overview',body:item.summary},
    {type:'text',title:'Learn',body:item.learn},
    {type:'code',title:'Example',code:{python:item.example,c:item.example,cpp:item.example}},
    ...(item.visual ? [{type:'visualization' as const,title:'Visualize',visual:item.visual}] : []),
    {type:'quiz',title:'Check your understanding',question:item.question,options:item.answers,answer:item.correct,explanation:item.takeaway},
    {type:'tip',title:'Keep in mind',body:item.takeaway},
    {type:'review',title:'Review',points:[item.summary,item.takeaway]},
  ];
  return {id,track,module:item.module,title:item.title,topic:item.title,difficulty:'Beginner',summary:item.summary,sections,exercises:item.exerciseIds.map(key=>makeExercise(taskById[key],track)),keywords:item.keywords ?? []};
}
const seeds: Record<TrackId,Seed[]> = {algorithms,python,c,cpp,embedded};
const titles: Record<TrackId,string> = {algorithms:'Algorithms',python:'Python',c:'C',cpp:'C++',embedded:'Embedded Systems'};
const descriptions: Record<TrackId,string> = {algorithms:'Estructuras, búsqueda y patrones para resolver problemas.',python:'De variables a módulos con práctica ejecutable.',c:'Fundamentos, punteros y memoria con C real.',cpp:'C++ moderno, STL y algoritmos.',embedded:'Firmware, periféricos y proyectos en una placa virtual.'};
export const tracks: LearningTrack[] = (Object.keys(seeds) as TrackId[]).map(id=>{
  const lessons = seeds[id].map(item=>toLesson(item,id));
  const names = [...new Set(lessons.map(item=>item.module))];
  return {id,title:titles[id],description:descriptions[id],accent:id==='embedded'?'blue':'purple',modules:names.map(name=>({id:slug(name),title:name,lessons:lessons.filter(item=>item.module===name)}))};
});
export const lessons = tracks.flatMap(track=>track.modules.flatMap(module=>module.lessons));
export const allExercises = lessons.flatMap(lesson=>lesson.exercises);
export const getTrack = (id:TrackId)=>tracks.find(track=>track.id===id)!;
export const getLesson = (id:string)=>lessons.find(lesson=>lesson.id===id);
