import { useEffect, useState } from 'react';
import { Bookmark, Check, Lightbulb, Play, RotateCcw } from 'lucide-react';
import { languages } from '../content/lessons';
import { runInWorker } from '../runner';
import { emptyAttempt } from '../storage/db';
import type { Exercise, Language, Progress, RunResult } from '../types';
import { CodeEditor } from './CodeEditor';

type Props={exercise:Exercise;language:Language;allowLanguageSwitch:boolean;onLanguage:(next:Language)=>void;dark:boolean;progress:Progress;update:(change:(value:Progress)=>Progress)=>void;notify:(message:string)=>void;mobileTab:'learn'|'code'|'output'};
type OutputTab='output'|'tests'|'console'|'errors';
export function ExerciseWorkspace({exercise,language,allowLanguageSwitch,onLanguage,dark,progress,update,notify,mobileTab}:Props){
  const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [result,setResult]=useState<RunResult|null>(null);const [error,setError]=useState('');const [tab,setTab]=useState<OutputTab>('tests');const [showRaw,setShowRaw]=useState(false);const [showSolution,setShowSolution]=useState(false);
  const key=`${exercise.id}:${language}`;const code=progress.drafts[key]??exercise.starter[language];const stats=progress.attempts[exercise.id]??emptyAttempt();
  function setCode(next:string){update(value=>({...value,drafts:{...value.drafts,[key]:next}}));}
  function updateStats(changes:Partial<typeof stats>){update(value=>({...value,attempts:{...value.attempts,[exercise.id]:{...(value.attempts[exercise.id]??emptyAttempt()),...changes}}}));}
  async function run(submit:boolean){if(busy)return;setBusy(true);setStatus('Preparing…');setResult(null);setError('');setTab('tests');const tests=exercise.tests.filter(item=>submit||!item.hidden);const response=await runInWorker({kind:'exercise',exercise,code,language,tests},setStatus);const now=new Date().toISOString();const passed=Boolean(response.result&&response.result.results.length===tests.length&&response.result.results.every(item=>item.passed));
    update(value=>{const prior=value.attempts[exercise.id]??emptyAttempt();return {...value,attempts:{...value.attempts,[exercise.id]:{...prior,runs:prior.runs+(submit?0:1),submits:prior.submits+(submit?1:0),failedSubmits:prior.failedSubmits+(submit&&!passed?1:0),lastAttempt:now,solvedAt:submit&&passed?(prior.solvedAt??now):prior.solvedAt}},solvedExercises:submit&&passed?[...new Set([...value.solvedExercises,exercise.id])]:value.solvedExercises,timeMinutes:value.timeMinutes+(response.result?Math.max(1,Math.ceil(response.result.durationMs/60000)):0)};});
    if(response.result)setResult(response.result);if(response.error)setError(response.error);if(submit&&passed)notify('¡Resuelto! Progreso guardado.');setBusy(false);
  }
  useEffect(()=>{function shortcut(event:KeyboardEvent){if(event.ctrlKey&&event.key==='Enter'){event.preventDefault();void run(event.shiftKey);}}window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);});
  const compilerLine=error.match(/(?:main\.(?:c|cpp):)?(\d+):(\d+):\s*(?:fatal\s+)?error:\s*([^\n]+)/);
  return <div className={`exercise-workspace mobile-${mobileTab}`}><div className="panel problem-panel mobile-problem"><div className="problem-header"><div><span className="eyebrow">PRACTICE · {exercise.difficulty.toUpperCase()}</span><h2>{exercise.title}</h2></div><button className={`bookmark-button ${progress.bookmarks.includes(`exercise:${exercise.id}`)?'saved':''}`} onClick={()=>update(value=>({...value,bookmarks:value.bookmarks.includes(`exercise:${exercise.id}`)?value.bookmarks.filter(item=>item!==`exercise:${exercise.id}`):[...value.bookmarks,`exercise:${exercise.id}`]}))} aria-label={progress.bookmarks.includes(`exercise:${exercise.id}`)?'Quitar ejercicio guardado':'Guardar ejercicio'}><Bookmark size={18}/></button><span className={`difficulty ${exercise.difficulty.toLowerCase()}`}>{exercise.difficulty}</span></div><p>{exercise.description}</p><div className="problem-detail"><strong>Example</strong><code>{exercise.examples[0]}</code></div><div className="problem-detail"><strong>Constraints</strong><span>{exercise.constraints.join(' · ')}</span></div><div className="hint-actions"><button onClick={()=>updateStats({hintsUsed:Math.min(exercise.hints.length,stats.hintsUsed+1)})}><Lightbulb size={16}/> Hint {stats.hintsUsed?`${stats.hintsUsed}/${exercise.hints.length}`:''}</button><button onClick={()=>{if(!showSolution)updateStats({solutionViewed:true});setShowSolution(!showSolution);}}>{showSolution?'Hide solution':'Solution'}</button></div>{stats.hintsUsed>0&&<div className="hint-box">{exercise.hints.slice(0,stats.hintsUsed).map((hint,i)=><p key={hint}><strong>Hint {i+1}:</strong> {hint}</p>)}</div>}{showSolution&&<div className="solution-box"><strong>Solution</strong><pre>{exercise.solutions[language]}</pre><p>{exercise.explanation}</p><small>Time: {exercise.complexity.time} · Space: {exercise.complexity.space}</small></div>}</div>
    <div className={`panel editor-panel ${mobileTab==='output'?'mobile-hidden':''}`}><div className="editor-toolbar"><div className="language-switch">{allowLanguageSwitch?languages.map(item=><button className={language===item.id?'active':''} key={item.id} onClick={()=>onLanguage(item.id)}>{item.name}</button>):<strong>{languages.find(item=>item.id===language)?.name}</strong>}</div><div className="editor-toolbar-actions"><button className="icon-button" title="Restablecer código" aria-label="Restablecer código" onClick={()=>setCode(exercise.starter[language])}><RotateCcw size={17}/></button><div className="editor-quick-actions"><button className="button secondary" disabled={busy} onClick={()=>void run(false)}><Play size={15}/> Run</button><button className="button primary" disabled={busy} onClick={()=>void run(true)}><Check size={15}/> Submit</button></div></div></div><CodeEditor code={code} onChange={setCode} language={language} dark={dark}/><div className="action-row"><button className="button secondary" disabled={busy} onClick={()=>void run(false)}><Play size={16}/> Run</button><button className="button primary" disabled={busy} onClick={()=>void run(true)}><Check size={16}/> Submit</button></div></div>
    <div className={`panel output-panel ${mobileTab!=='output'?'mobile-hidden':''}`} aria-live="polite"><div className="panel-heading"><div><span className="eyebrow">TEST RUNNER</span><h2>Resultados</h2></div>{result&&<span className="result-duration">{result.durationMs} ms</span>}</div><div className="output-tabs" role="tablist">{(['output','tests','console','errors'] as const).map(item=><button role="tab" aria-selected={tab===item} className={tab===item?'active':''} key={item} onClick={()=>setTab(item)}>{item.toUpperCase()}</button>)}</div>{busy?<div className="output-empty"><span className="spinner"/>{status}</div>:tab==='errors'?(error||result?.error?<div className="compiler-error">{compilerLine?<><strong>Compilation Error · Line {compilerLine[1]}</strong><p>{compilerLine[3]}</p><button onClick={()=>setShowRaw(!showRaw)}>{showRaw?'Hide':'Show'} raw compiler output</button>{showRaw&&<pre className="error-output">{error}</pre>}</>:<pre className="error-output">{error||result?.error}</pre>}</div>:<div className="output-empty">No errors.</div>):tab==='console'?<pre className="stdout-box">{result?.stdout||'No console output yet.'}</pre>:tab==='output'?<div className="output-summary">{result?<><div className={`result-summary ${result.results.every(item=>item.passed)?'pass':'fail'}`}>{result.results.filter(item=>item.passed).length} / {result.results.length} tests passed</div><p>{result.results.every(item=>item.passed)?'Correct output for these tests.':'Review the failed tests below.'}</p></>:<div className="output-empty">Run code to see output.</div>}</div>:result?<div className="test-results"><div className={`result-summary ${result.results.every(item=>item.passed)?'pass':'fail'}`}>{result.results.filter(item=>item.passed).length} / {result.results.length} tests passed</div>{result.results.map((item,i)=><div className={`test-row ${item.passed?'passed':'failed'}`} key={i}><div><strong>Test {i+1}{item.hidden?' · Hidden':''}</strong><span>{item.passed?'PASS':'FAIL'}</span></div>{!item.hidden&&<><small>Input: <code>{item.input}</code></small><small>Expected: <code>{item.expected}</code></small><small>Received: <code>{item.received}</code></small></>}{item.error&&!item.hidden&&<pre className="error-output">{item.error}</pre>}{item.error&&item.hidden&&<small>Hidden test failed.</small>}</div>)}</div>:error?<div className="output-empty">Execution failed. Open Errors for details.</div>:<div className="output-empty">Run shows visible tests. Submit checks all tests.</div>}</div><small className="attempt-line">Runs {stats.runs} · Submits {stats.submits}{stats.solvedAt?' · Solved':''}</small></div>;
}
