import { ArrowRight, Braces, Check, Code2, Cpu, Layers3, WifiOff } from 'lucide-react';
import type { TrackId } from '../types';

export function LandingPage({ onStart }: { onStart: (track?: TrackId) => void }) {
  return <div className="landing-page">
    <header className="landing-header"><button className="landing-brand" onClick={() => onStart()}><span><Braces size={20}/></span><strong>FORGE THE CODE</strong></button><nav aria-label="Main navigation"><a href="#curriculum">Curriculum</a><a href="#offline">Offline learning</a><button className="button secondary" onClick={() => onStart()}>Open app <ArrowRight size={16}/></button></nav></header>
    <main>
      <section className="landing-hero">
        <div className="landing-copy"><span className="eyebrow">AN INTERACTIVE PROGRAMMING BOOK</span><h1>Forge the Code</h1><p className="landing-tagline">Master code by building it.</p><p className="landing-lead">Learn algorithms, Python, C, C++ and embedded systems through clear lessons, real code and hands-on visual labs.</p><div className="landing-actions"><button className="button primary" onClick={() => onStart()}><Code2 size={17}/>Start learning</button><button className="button secondary" onClick={() => onStart('algorithms')}>Explore curriculum <ArrowRight size={16}/></button></div><div className="landing-proof"><span><Check size={15}/> Runs locally</span><span><WifiOff size={15}/> Works offline after setup</span></div></div>
        <div className="landing-preview" aria-label="Preview of a binary search lesson and code editor"><div className="preview-top"><span><i/>Binary Search</span><small>ALGORITHMS · SEARCHING</small></div><div className="preview-state"><span>Target <strong>23</strong></span><span>Step <strong>3 / 6</strong></span></div><div className="preview-array" aria-label="Sorted array with midpoint highlighted">{[2,5,8,12,17,23,31,40,52].map((value,index)=><span className={index===5?'found':index<5?'discarded':''} key={value}><small>{index===5?'mid':''}</small>{value}</span>)}</div><p className="preview-explain">17 is less than 23. Search the right half.</p><pre><code><b>int</b> mid = left + (right - left) / 2;{`\n`}<b>if</b> (values[mid] == target) <b>return</b> mid;{`\n`}left = mid + 1;</code></pre><div className="preview-result"><Check size={16}/> 6 / 6 visible tests passed</div></div>
      </section>
      <section className="landing-pillars"><article><span><Layers3 size={20}/></span><h2>Understand the idea</h2><p>Short explanations and step-by-step visualizations make the hard parts easier to see.</p></article><article><span><Code2 size={20}/></span><h2>Build real fluency</h2><p>Write Python, C and C++ in a CodeMirror editor, then run your work locally in the browser.</p></article><article><span><Cpu size={20}/></span><h2>Explore embedded systems</h2><p>Build firmware for a virtual board with GPIO, ADC, PWM, UART and event traces.</p></article></section>
      <section id="curriculum" className="landing-curriculum"><div><span className="eyebrow">A CLEAR PATH FROM FIRST STEPS TO SYSTEMS</span><h2>One place to learn how software works.</h2></div><div className="curriculum-list">{[['Algorithms','10 lessons · 17 exercises'],['Python','8 lessons · 12 exercises'],['C','8 lessons · 11 exercises'],['C++','10 lessons · 15 exercises'],['Embedded Systems','10 lessons · 3 projects']].map(([name,detail],index)=><button key={name} onClick={() => onStart(index===4?'embedded':index===0?'algorithms':index===1?'python':index===2?'c':'cpp')}><span>0{index+1}</span><strong>{name}</strong><small>{detail}</small><ArrowRight size={17}/></button>)}</div></section>
      <section id="offline" className="landing-offline"><div><WifiOff size={22}/><span className="eyebrow">DESIGNED FOR OFFLINE LEARNING</span></div><h2>Your downloaded lessons and runtimes stay on this device.</h2><p>Prepare Forge for offline use once. Then keep reading, coding and practicing without a connection.</p><button className="button secondary" onClick={() => onStart()}>See offline settings <ArrowRight size={16}/></button></section>
      <section className="landing-final"><div><span className="eyebrow">START WITH A SMALL STEP</span><h2>Make the next idea click.</h2></div><button className="button primary" onClick={() => onStart()}>Start learning <ArrowRight size={16}/></button></section>
    </main>
    <footer className="landing-footer"><span>FORGE THE CODE</span><span>Master code by building it.</span><small>No account required. Progress stays on this device.</small></footer>
  </div>;
}
