import { useEffect, useState } from 'react';
import { Download, Wifi, WifiOff } from 'lucide-react';
import type { Progress } from '../types';

type Status={ready:boolean;done:number;total:number;sizes:{lessons:number;python:number;native:number;other:number};groups:Record<'lessons'|'python'|'native'|'other',{done:number;total:number}>};
const mb=(bytes:number)=>`${(bytes/1024/1024).toFixed(1)} MB`;
export function OfflineManager({progress}:{progress:Progress}){
  const [online,setOnline]=useState(navigator.onLine);const [state,setState]=useState<'checking'|'idle'|'downloading'|'ready'|'error'>('checking');const [status,setStatus]=useState<Status|null>(null);const [downloaded,setDownloaded]=useState({done:0,total:0});const [message,setMessage]=useState('Checking local resources…');const [localBytes,setLocalBytes]=useState(0);
  useEffect(()=>{const connectivity=()=>setOnline(navigator.onLine);const onMessage=(event:MessageEvent)=>{if(event.data?.type==='OFFLINE_PROGRESS'){setDownloaded({done:event.data.done,total:event.data.total});setState('downloading');setMessage(`${event.data.done} / ${event.data.total} resources cached`);}if(event.data?.type==='OFFLINE_STATUS'){const value=event.data as Status;setStatus(value);setDownloaded({done:value.done,total:value.total});setState(value.ready?'ready':'idle');setMessage(value.ready?'Ready for offline use':`${value.done} / ${value.total} resources cached`);}if(event.data?.type==='OFFLINE_ERROR'){setState('error');setMessage(`Could not cache ${event.data.asset}. ${event.data.message??'Retry while online.'}`);}};window.addEventListener('online',connectivity);window.addEventListener('offline',connectivity);navigator.serviceWorker?.addEventListener('message',onMessage);navigator.serviceWorker?.ready.then(registration=>registration.active?.postMessage({type:'GET_OFFLINE_STATUS'})).catch(()=>{setState('error');setMessage('Offline status is unavailable. Open this page on localhost or HTTPS.');});navigator.storage?.estimate().then(value=>setLocalBytes(value.usage??0)).catch(()=>{});return()=>{window.removeEventListener('online',connectivity);window.removeEventListener('offline',connectivity);navigator.serviceWorker?.removeEventListener('message',onMessage);};},[]);
  async function download(){setDownloaded({done:0,total:0});setState('downloading');setMessage('Preparing Forge the Code for offline use…');try{const registration=await navigator.serviceWorker.ready;if(!registration.active)throw new Error('Service Worker unavailable. Use HTTPS or localhost.');registration.active.postMessage({type:'DOWNLOAD_OFFLINE'});}catch(error){setState('error');setMessage(String(error));}}
  const cachedTotal=status?Object.values(status.sizes).reduce((a,b)=>a+b,0):0;const progressBytes=new Blob([JSON.stringify(progress)]).size;const total=cachedTotal+progressBytes;
  const categories:[string,keyof Status['sizes'],keyof Status['groups']][]=[['Application & lessons','lessons','lessons'],['Python runtime','python','python'],['C / C++ runtime','native','native'],['Other assets','other','other']];
  return <div className="offline-manager"><div className="offline-header"><span className="connectivity">{online?<Wifi size={16}/>:<WifiOff size={16}/>} {online?'Online':'Offline'}</span><strong className={state==='ready'?'offline-ready':''}>{state==='ready'?'✓ Offline Ready':state==='downloading'?'Preparing for offline use':state==='checking'?'Checking offline content':'Offline content incomplete'}</strong></div><p aria-live="polite">{message}</p>{state==='downloading'&&<progress className="offline-progress" aria-label="Offline download progress" value={downloaded.done} max={downloaded.total||1}/>}<div className="offline-categories">{categories.map(([name,sizeKey,groupKey])=>{const group=status?.groups[groupKey];const ready=Boolean(group&&group.total>0&&group.done===group.total);return <div key={name}><span>{name}</span><strong className={ready?'resource-ready':''}>{ready?'✓ Ready':group?(`${group.done}/${group.total} cached`):mb(Number(status?.sizes[sizeKey]??0))}</strong></div>;})}<div><span>Progress (IndexedDB)</span><strong>{mb(progressBytes)}</strong></div><div><span>Total stored</span><strong>{mb(total)}</strong></div></div><p className="storage-estimate">Browser storage used on this origin: {mb(localBytes)}. Includes local data and caches.</p><button className="button secondary" onClick={()=>void download()} disabled={!online||state==='downloading'}><Download size={16}/>{state==='ready'?'Refresh offline content':'Prepare for offline use'}</button></div>;
}
