import { useEffect, useState } from 'react';
import type { LessonSection } from '../types';

type Visual = Extract<LessonSection,{type:'visualization'}>['visual'];
const searchValues=[1,3,5,7,9,11,15];
const searchSteps=[{left:0,right:6,mid:3,note:'7 < 11: descarta la mitad izquierda.'},{left:4,right:6,mid:5,note:'11 = 11: objetivo encontrado.'}];

export function Visualization({kind}:{kind:Visual}) {
  const [step,setStep]=useState(0);
  const [auto,setAuto]=useState(false);const [speed,setSpeed]=useState(1);
  const [items,setItems]=useState([2,5,8]);
  const [next,setNext]=useState(13);
  const [value,setValue]=useState(13);
  const [treeOrder,setTreeOrder]=useState<'bfs'|'pre'|'in'|'post'>('bfs');
  const [register,setRegister]=useState(0);
  const setNumber=(number:number)=>{if(kind==='register')setRegister(number);else setValue(number);};
  useEffect(()=>{if(!auto||kind!=='binary-search')return;const timer=window.setInterval(()=>setStep(current=>(current+1)%searchSteps.length),1300/speed);return()=>window.clearInterval(timer);},[auto,kind,speed]);
  if(kind==='binary-search') {const current=searchSteps[step];return <div className="interactive-visual"><div className="visual-header"><strong>Target = 11</strong><span>left {current.left} · mid {current.mid} · right {current.right}</span></div><div className="array-cells">{searchValues.map((n,i)=><div key={i} className={`array-cell ${i===current.mid?'active':''} ${i<current.left||i>current.right?'muted-cell':''}`}><small>{i}</small><strong>{n}</strong><span>{i===current.mid?'MID':i===current.left?'L':i===current.right?'R':' '}</span></div>)}</div><p>{current.note}</p><div className="visual-actions"><button onClick={()=>setStep(Math.max(0,step-1))}>Previous</button><button onClick={()=>setStep(Math.min(searchSteps.length-1,step+1))}>Next</button><button onClick={()=>setAuto(!auto)}>{auto?'Pause':'Auto'}</button><button onClick={()=>{setStep(0);setAuto(false);}}>Reset</button><label className="visual-speed">Speed<select aria-label="Playback speed" value={speed} onChange={event=>setSpeed(Number(event.target.value))}><option value={0.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label></div></div>;}
  if(kind==='stack'||kind==='queue'||kind==='linked-list') return <div className="interactive-visual"><div className="visual-header"><strong>{kind==='stack'?'LIFO · Stack':kind==='queue'?'FIFO · Queue':'Linked nodes'}</strong><span>{items.length} values</span></div><div className={`structure-cells ${kind}`}>{items.length?items.map((item,i)=><span className="node" key={`${i}-${item}`}>{item}{kind==='linked-list'&&<small>→</small>}</span>):<span className="empty-visual">Empty</span>}{kind==='linked-list'&&<span>null</span>}</div><p>{kind==='stack'?'Push and pop at the top.':kind==='queue'?'Add at the back, remove from the front.':'Each node points to the next node.'}</p><div className="visual-actions"><button onClick={()=>{setItems([...items,next]);setNext(next+3);}}>{kind==='stack'?'Push':'Add'}</button><button disabled={!items.length} onClick={()=>setItems(kind==='stack'?items.slice(0,-1):items.slice(1))}>{kind==='stack'?'Pop':'Remove front'}</button><button onClick={()=>{setItems([2,5,8]);setNext(13);}}>Reset</button></div></div>;
  if(kind==='tree'){const labels={bfs:'4, 2, 6, 1, 3, 5, 7',pre:'4, 2, 1, 3, 6, 5, 7',in:'1, 2, 3, 4, 5, 6, 7',post:'1, 3, 2, 5, 7, 6, 4'};return <div className="interactive-visual"><div className="tree-visual"><div>④</div><div>② ───── ⑥</div><div>① ─ ③　　 ⑤ ─ ⑦</div></div><div className="visual-actions">{(['bfs','pre','in','post'] as const).map(order=><button className={treeOrder===order?'selected':''} key={order} onClick={()=>setTreeOrder(order)}>{order.toUpperCase()}</button>)}</div><p><strong>Visit order:</strong> {labels[treeOrder]}</p></div>;}
  if(kind==='memory')return <div className="interactive-visual"><div className="visual-header"><strong>Memory</strong><span>int *p = &amp;values[1]</span></div><div className="memory-grid"><span>Address</span><span>Value</span><span>0x1000</span><strong>25</strong><span className="pointed">0x1004 ← p</span><strong className="pointed">8</strong><span>0x1008</span><strong>14</strong></div><p>Dereferencing <code>*p</code> reads 8. Adding 1 to p moves one int, typically four bytes in this illustration.</p></div>;
  if(kind==='binary-hex'||kind==='register')return <div className="interactive-visual"><div className="number-inputs"><label>Decimal<input type="number" min="0" max="255" value={kind==='register'?register:value} onChange={e=>setNumber(Math.max(0,Math.min(255,Number(e.target.value)||0)))}/></label><label>Binary<input aria-label="Binary" value={(kind==='register'?register:value).toString(2).padStart(8,'0')} onChange={e=>{if(/^[01]{0,8}$/.test(e.target.value))setNumber(parseInt(e.target.value||'0',2));}}/></label><label>Hex<input aria-label="Hexadecimal" value={(kind==='register'?register:value).toString(16).toUpperCase().padStart(2,'0')} onChange={e=>{if(/^[0-9a-fA-F]{0,2}$/.test(e.target.value))setNumber(parseInt(e.target.value||'0',16));}}/></label></div><div className="bit-grid">{Array.from({length:8},(_,index)=>{const bit=7-index;const on=Boolean((kind==='register'?register:value)&(1<<bit));return <button key={bit} aria-label={`Bit ${bit}: ${on?'on':'off'}`} aria-pressed={on} onClick={()=>setNumber((kind==='register'?register:value)^(1<<bit))}><small>{bit}</small><strong>{on?1:0}</strong></button>;})}</div>{kind==='register'&&<><p><code>GPIO_CTRL |= (1u &lt;&lt; 3);</code> sets bit 3 and preserves the other bits.</p><div className="visual-actions"><button onClick={()=>setRegister(register|(1<<3))}>Enable bit 3</button><button onClick={()=>setRegister(register&~(1<<3))}>Clear bit 3</button><button onClick={()=>setRegister(0)}>Reset</button></div></>}</div>;
  return null;
}
